# Generated by Django 6.0.1 on 2026-02-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
